from django.urls import path
from Accounts.views import *
urlpatterns = [
    path('query',general,name='general_query'),
    path('branch',branch,name="branch-queries"),
    path('branch/query-1',branch_query_1,name="bq-1"),
    path('branch/query-2',branch_query_2,name="bq-2"),
    path('branch/query-3',branch_query_3,name="bq-3"),
    path('branch/query-4',branch_query_4,name="bq-4"),
    path('branch/query-5',branch_query_5,name="bq-5"),
    path('branch/query-6',branch_query_6,name="bq-6"),
    path('branch/query-7',branch_query_7,name="bq-7"),
    path('branch/query-8',branch_query_8,name="bq-8"),
    path('client',client,name="client-queries"),
    path("client/query-1",client_query_1,name="cq-1"),
    path("client/query-2",client_query_2,name="cq-2"),
    path("client/query-3",client_query_3,name="cq-3"),
    path("client/query-4",client_query_4,name="cq-4"),
    path("client/query-5",client_query_5,name="cq-5"),
    path("client/query-6",client_query_6,name="cq-6"),
    path('manager',manager,name="manager-queries"),
    path("manager/query-1",manager_query_1, name="mq-1"),
    path('owner',owner,name="owner-queries"),
    path("owner/query-1",owner_query_1,name="oq-1"),
    path("owner/query-2",owner_query_2,name="oq-2"),
    path('property',property,name="property-queries"),
    path('property/query-1',property_query_1,name="pq-1"),
    path('property/query-2',property_query_2,name="pq-2"),
    path('property/query-3',property_query_3,name="pq-3"),
    path('property/query-4',property_query_4,name="pq-4"),
    path('property/query-5',property_query_5,name="pq-5"),
    path('property/query-6',property_query_6,name="pq-6"),
    path('property/query-7',property_query_7,name="pq-7"),
    path('property/query-8',property_query_8,name="pq-8"),
    path('property/query-9',property_query_9,name="pq-9"),
    path('property/query-10',property_query_10,name="pq-10"),
    path('property/query-11',property_query_11,name="pq-11"),
    path('staff',staff,name="staff-queries"),
    path('staff/query-1',staff_query_1,name="sq-1"),
    path('staff/query-2',staff_query_2,name="sq-2"),
    path('staff/query-3',staff_query_3,name="sq-3"),
    path('staff/query-4',staff_query_4,name="sq-4"),
    path('staff/query-5',staff_query_5,name="sq-5"),
    path('staff/query-6',staff_query_6,name="sq-6"),
]

